# CatBoost Algorithm

CatBoost is a state-of-the-art open-source gradient boosting on decision trees library. It's simple and easy to use. And is now regularly one of the top algorithms used in data science competitions as it produces very good results without extensive data clean-up or feature engineering.

In [2]:
# !pip install catboost

In [3]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [4]:
# data import titanic
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

# pre-processing

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [6]:
df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [7]:
# impute missing values using knn imputers in age
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)
df['age'] = imputer.fit_transform(df[['age']])

# impute embarked missing values using pandas
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])
# drop deck column
df.drop('deck', axis=1, inplace=True)

# df missing values
df.isnull().sum().sort_values(ascending=False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     891 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  embark_town  891 non-null    str
 12  alive        891 non-null    str
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(5)
memory usage: 79.4 KB

In [9]:
# convert each category column to category
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
# add this as a new column in the dataframe
df[categorical_cols] = df[categorical_cols].astype('category')

C:\Users\pc\AppData\Local\Temp\ipykernel_8512\788406418.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object', 'category']).columns

In [10]:
# split data into X and y
X = df.drop('survived', axis=1)
y = df['survived']

# split data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
# run the catboost classifier
model = CatBoostClassifier(iterations=100,
                           learning_rate=0.1,
                           depth=3,
                           loss_function='Logloss',
                           eval_metric='Accuracy',
                           random_seed=42,
                           verbose=False)

# train the model
model.fit(X_train, y_train, cat_features=categorical_cols.tolist())

# predictions
y_pred = model.predict(X_test)

# evaluate the model
print(f'Accuracy Score: {accuracy_score(y_test, y_pred)}')
print(f'Confusion Matrix: \n {confusion_matrix(y_test, y_pred)}')
print(f'Classification Report: \n {classification_report(y_test, y_pred)}')

Accuracy Score: 1.0
Confusion Matrix:
 [[105   0]
 [  0  74]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       105
           1       1.00      1.00      1.00        74

    accuracy                           1.00       179
   macro avg       1.00      1.00      1.00       179
weighted avg       1.00      1.00      1.00       179

In [12]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [14]:
df.isnull().sum().sort_values(ascending=False)

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [16]:
X = df.drop('species', axis=1)
y = df['species']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = CatBoostClassifier()
model.fit(X_train, y_train, cat_features=X_train.select_dtypes(include=['object', 'category']).columns.tolist())

Learning rate set to 0.071017
0:	learn: 1.0144505	total: 15.3ms	remaining: 15.3s
1:	learn: 0.9424962	total: 16.6ms	remaining: 8.27s
2:	learn: 0.8790301	total: 17.7ms	remaining: 5.88s
3:	learn: 0.8213931	total: 18.8ms	remaining: 4.68s
4:	learn: 0.7787524	total: 19.9ms	remaining: 3.96s
5:	learn: 0.7279856	total: 21ms	remaining: 3.48s
6:	learn: 0.6912572	total: 21.7ms	remaining: 3.07s
7:	learn: 0.6583879	total: 22.3ms	remaining: 2.77s
8:	learn: 0.6234511	total: 24.2ms	remaining: 2.67s
9:	learn: 0.5947136	total: 25ms	remaining: 2.48s
10:	learn: 0.5642619	total: 25.7ms	remaining: 2.31s
11:	learn: 0.5369460	total: 26.3ms	remaining: 2.17s
12:	learn: 0.5121796	total: 27ms	remaining: 2.05s
13:	learn: 0.4842852	total: 27.3ms	remaining: 1.92s
14:	learn: 0.4637429	total: 28ms	remaining: 1.83s
15:	learn: 0.4430565	total: 28.6ms	remaining: 1.76s
16:	learn: 0.4249106	total: 31.8ms	remaining: 1.84s
17:	learn: 0.4093680	total: 32.8ms	remaining: 1.79s
18:	learn: 0.3927312	total: 33.5ms	remaining: 1.73s
19:	learn: 0.3775090	total: 34.1ms	remaining: 1.67s
20:	learn: 0.3626542	total: 34.7ms	remaining: 1.62s
21:	learn: 0.3527045	total: 35.3ms	remaining: 1.57s
22:	learn: 0.3421974	total: 36ms	remaining: 1.53s
23:	learn: 0.3311294	total: 36.6ms	remaining: 1.49s
24:	learn: 0.3194751	total: 37.5ms	remaining: 1.46s
25:	learn: 0.3107495	total: 38.4ms	remaining: 1.44s
26:	learn: 0.2993516	total: 39.1ms	remaining: 1.41s
27:	learn: 0.2895478	total: 39.8ms	remaining: 1.38s
28:	learn: 0.2796955	total: 40.2ms	remaining: 1.34s
29:	learn: 0.2714519	total: 40.8ms	remaining: 1.32s
30:	learn: 0.2608803	total: 41.4ms	remaining: 1.29s
31:	learn: 0.2536045	total: 42ms	remaining: 1.27s
32:	learn: 0.2451855	total: 42.7ms	remaining: 1.25s
33:	learn: 0.2391014	total: 43.4ms	remaining: 1.23s
34:	learn: 0.2316281	total: 44ms	remaining: 1.21s
35:	learn: 0.2258914	total: 44.6ms	remaining: 1.19s
36:	learn: 0.2209424	total: 45.2ms	remaining: 1.18s
37:	learn: 0.2143643	total: 45.8ms	remaining: 1.16s
38:	learn: 0.2099476	total: 46.6ms	remaining: 1.15s
39:	learn: 0.2044738	total: 47.2ms	remaining: 1.13s
40:	learn: 0.2004731	total: 47.8ms	remaining: 1.12s
41:	learn: 0.1955927	total: 48.4ms	remaining: 1.1s
42:	learn: 0.1905310	total: 49ms	remaining: 1.09s
43:	learn: 0.1857510	total: 49.6ms	remaining: 1.08s
44:	learn: 0.1814081	total: 50.3ms	remaining: 1.07s
45:	learn: 0.1780659	total: 51ms	remaining: 1.06s
46:	learn: 0.1739549	total: 52ms	remaining: 1.05s
47:	learn: 0.1702103	total: 52.6ms	remaining: 1.04s
48:	learn: 0.1676878	total: 53.5ms	remaining: 1.04s
49:	learn: 0.1639098	total: 54.2ms	remaining: 1.03s
50:	learn: 0.1601189	total: 54.8ms	remaining: 1.02s
51:	learn: 0.1572164	total: 57.4ms	remaining: 1.04s
52:	learn: 0.1543431	total: 59ms	remaining: 1.05s
53:	learn: 0.1525400	total: 60.1ms	remaining: 1.05s
54:	learn: 0.1493916	total: 60.9ms	remaining: 1.05s
55:	learn: 0.1458460	total: 61.9ms	remaining: 1.04s
56:	learn: 0.1440560	total: 62.8ms	remaining: 1.04s
57:	learn: 0.1411764	total: 63.4ms	remaining: 1.03s
58:	learn: 0.1382724	total: 63.9ms	remaining: 1.02s
59:	learn: 0.1364335	total: 64.4ms	remaining: 1.01s
60:	learn: 0.1342267	total: 64.9ms	remaining: 1000ms
61:	learn: 0.1320805	total: 66ms	remaining: 999ms
62:	learn: 0.1295520	total: 67.3ms	remaining: 1s
63:	learn: 0.1266437	total: 68.1ms	remaining: 996ms
64:	learn: 0.1246431	total: 68.6ms	remaining: 987ms
65:	learn: 0.1226912	total: 69.2ms	remaining: 979ms
66:	learn: 0.1204539	total: 69.7ms	remaining: 971ms
67:	learn: 0.1180308	total: 70.2ms	remaining: 963ms
68:	learn: 0.1163097	total: 70.8ms	remaining: 955ms
69:	learn: 0.1141911	total: 71.3ms	remaining: 947ms
70:	learn: 0.1122488	total: 71.8ms	remaining: 940ms
71:	learn: 0.1101300	total: 72.5ms	remaining: 934ms
72:	learn: 0.1087376	total: 73ms	remaining: 927ms
73:	learn: 0.1072051	total: 73.5ms	remaining: 920ms
74:	learn: 0.1056190	total: 74.1ms	remaining: 914ms
75:	learn: 0.1039900	total: 74.6ms	remaining: 907ms
76:	learn: 0.1026141	total: 75.1ms	remaining: 900ms
77:	learn: 0.1012645	total: 75.6ms	remaining: 894ms
78:	learn: 0.0999636	total: 76.2ms	remaining: 888ms
79:	learn: 0.0986039	total: 76.7ms	remaining: 882ms
80:	learn: 0.0973402	total: 77.2ms	remaining: 876ms
81:	learn: 0.0963303	total: 77.7ms	remaining: 870ms
82:	learn: 0.0949777	total: 78.2ms	remaining: 864ms
83:	learn: 0.0935951	total: 79.6ms	remaining: 869ms
84:	learn: 0.0925139	total: 80.3ms	remaining: 865ms
85:	learn: 0.0913463	total: 80.9ms	remaining: 859ms
86:	learn: 0.0902440	total: 81.4ms	remaining: 854ms
87:	learn: 0.0891552	total: 81.9ms	remaining: 849ms
88:	learn: 0.0881584	total: 82.4ms	remaining: 844ms
89:	learn: 0.0864535	total: 82.9ms	remaining: 839ms
90:	learn: 0.0855925	total: 83.5ms	remaining: 834ms
91:	learn: 0.0846171	total: 84ms	remaining: 829ms
92:	learn: 0.0837302	total: 84.5ms	remaining: 824ms
93:	learn: 0.0827383	total: 85ms	remaining: 820ms
94:	learn: 0.0811931	total: 85.7ms	remaining: 816ms
95:	learn: 0.0800089	total: 86.4ms	remaining: 813ms
96:	learn: 0.0791131	total: 87.1ms	remaining: 811ms
97:	learn: 0.0782170	total: 87.7ms	remaining: 807ms
98:	learn: 0.0774043	total: 88.3ms	remaining: 804ms
99:	learn: 0.0765762	total: 88.9ms	remaining: 800ms
100:	learn: 0.0756390	total: 89.5ms	remaining: 797ms
101:	learn: 0.0746061	total: 90.1ms	remaining: 793ms
102:	learn: 0.0734781	total: 90.7ms	remaining: 790ms
103:	learn: 0.0723942	total: 91.3ms	remaining: 787ms
104:	learn: 0.0714809	total: 91.9ms	remaining: 784ms
105:	learn: 0.0707045	total: 92.9ms	remaining: 783ms
106:	learn: 0.0697267	total: 93.5ms	remaining: 781ms
107:	learn: 0.0687674	total: 94.1ms	remaining: 777ms
108:	learn: 0.0679397	total: 94.8ms	remaining: 775ms
109:	learn: 0.0673130	total: 95.4ms	remaining: 771ms
110:	learn: 0.0667269	total: 96ms	remaining: 769ms
111:	learn: 0.0659101	total: 96.6ms	remaining: 766ms
112:	learn: 0.0651933	total: 97.2ms	remaining: 763ms
113:	learn: 0.0641984	total: 97.8ms	remaining: 760ms
114:	learn: 0.0634900	total: 98.3ms	remaining: 757ms
115:	learn: 0.0626172	total: 98.9ms	remaining: 754ms
116:	learn: 0.0619172	total: 99.7ms	remaining: 753ms
117:	learn: 0.0613318	total: 100ms	remaining: 750ms
118:	learn: 0.0607494	total: 101ms	remaining: 747ms
119:	learn: 0.0601309	total: 102ms	remaining: 745ms
120:	learn: 0.0595159	total: 102ms	remaining: 742ms
121:	learn: 0.0586334	total: 103ms	remaining: 740ms
122:	learn: 0.0577536	total: 103ms	remaining: 737ms
123:	learn: 0.0570026	total: 104ms	remaining: 735ms
124:	learn: 0.0565342	total: 105ms	remaining: 732ms
125:	learn: 0.0557539	total: 105ms	remaining: 730ms
126:	learn: 0.0552961	total: 106ms	remaining: 727ms
127:	learn: 0.0547861	total: 107ms	remaining: 727ms
128:	learn: 0.0541767	total: 108ms	remaining: 729ms
129:	learn: 0.0536834	total: 109ms	remaining: 727ms
130:	learn: 0.0533008	total: 110ms	remaining: 729ms
131:	learn: 0.0527310	total: 111ms	remaining: 728ms
132:	learn: 0.0523332	total: 112ms	remaining: 727ms
133:	learn: 0.0517023	total: 112ms	remaining: 726ms
134:	learn: 0.0511588	total: 113ms	remaining: 725ms
135:	learn: 0.0507966	total: 114ms	remaining: 723ms
136:	learn: 0.0502306	total: 114ms	remaining: 720ms
137:	learn: 0.0497282	total: 115ms	remaining: 718ms
138:	learn: 0.0493065	total: 116ms	remaining: 716ms
139:	learn: 0.0487645	total: 116ms	remaining: 714ms
140:	learn: 0.0482723	total: 117ms	remaining: 711ms
141:	learn: 0.0479220	total: 117ms	remaining: 709ms
142:	learn: 0.0474765	total: 118ms	remaining: 707ms
143:	learn: 0.0470794	total: 119ms	remaining: 705ms
144:	learn: 0.0466702	total: 119ms	remaining: 704ms
145:	learn: 0.0463042	total: 120ms	remaining: 703ms
146:	learn: 0.0458321	total: 121ms	remaining: 700ms
147:	learn: 0.0454702	total: 123ms	remaining: 708ms
148:	learn: 0.0450233	total: 124ms	remaining: 707ms
149:	learn: 0.0446080	total: 125ms	remaining: 706ms
150:	learn: 0.0442548	total: 125ms	remaining: 703ms
151:	learn: 0.0438954	total: 126ms	remaining: 701ms
152:	learn: 0.0435539	total: 126ms	remaining: 698ms
153:	learn: 0.0431634	total: 127ms	remaining: 696ms
154:	learn: 0.0427788	total: 127ms	remaining: 693ms
155:	learn: 0.0424854	total: 128ms	remaining: 691ms
156:	learn: 0.0421240	total: 128ms	remaining: 689ms
157:	learn: 0.0417497	total: 129ms	remaining: 686ms
158:	learn: 0.0414537	total: 129ms	remaining: 684ms
159:	learn: 0.0409807	total: 130ms	remaining: 682ms
160:	learn: 0.0406471	total: 130ms	remaining: 679ms
161:	learn: 0.0404002	total: 131ms	remaining: 677ms
162:	learn: 0.0401312	total: 131ms	remaining: 675ms
163:	learn: 0.0398210	total: 132ms	remaining: 672ms
164:	learn: 0.0394326	total: 132ms	remaining: 670ms
165:	learn: 0.0391914	total: 133ms	remaining: 668ms
166:	learn: 0.0389570	total: 133ms	remaining: 666ms
167:	learn: 0.0386927	total: 134ms	remaining: 664ms
168:	learn: 0.0383121	total: 135ms	remaining: 662ms
169:	learn: 0.0380003	total: 135ms	remaining: 659ms
170:	learn: 0.0377492	total: 137ms	remaining: 664ms
171:	learn: 0.0373849	total: 138ms	remaining: 662ms
172:	learn: 0.0371730	total: 138ms	remaining: 660ms
173:	learn: 0.0369504	total: 139ms	remaining: 658ms
174:	learn: 0.0366607	total: 139ms	remaining: 656ms
175:	learn: 0.0362737	total: 140ms	remaining: 654ms
176:	learn: 0.0359726	total: 140ms	remaining: 653ms
177:	learn: 0.0358108	total: 141ms	remaining: 651ms
178:	learn: 0.0355894	total: 142ms	remaining: 649ms
179:	learn: 0.0353372	total: 142ms	remaining: 647ms
180:	learn: 0.0350173	total: 143ms	remaining: 645ms
181:	learn: 0.0347794	total: 143ms	remaining: 643ms
182:	learn: 0.0345305	total: 144ms	remaining: 641ms
183:	learn: 0.0343078	total: 144ms	remaining: 639ms
184:	learn: 0.0340992	total: 145ms	remaining: 637ms
185:	learn: 0.0338534	total: 145ms	remaining: 635ms
186:	learn: 0.0336135	total: 146ms	remaining: 634ms
187:	learn: 0.0334055	total: 146ms	remaining: 632ms
188:	learn: 0.0331960	total: 147ms	remaining: 630ms
189:	learn: 0.0329494	total: 147ms	remaining: 629ms
190:	learn: 0.0327824	total: 148ms	remaining: 627ms
191:	learn: 0.0325356	total: 149ms	remaining: 625ms
192:	learn: 0.0323577	total: 149ms	remaining: 623ms
193:	learn: 0.0321178	total: 150ms	remaining: 622ms
194:	learn: 0.0319593	total: 151ms	remaining: 623ms
195:	learn: 0.0317739	total: 152ms	remaining: 622ms
196:	learn: 0.0315725	total: 152ms	remaining: 621ms
197:	learn: 0.0313575	total: 153ms	remaining: 622ms
198:	learn: 0.0312009	total: 154ms	remaining: 620ms
199:	learn: 0.0310211	total: 155ms	remaining: 619ms
200:	learn: 0.0308472	total: 155ms	remaining: 617ms
201:	learn: 0.0306919	total: 156ms	remaining: 616ms
202:	learn: 0.0305315	total: 156ms	remaining: 614ms
203:	learn: 0.0303349	total: 157ms	remaining: 612ms
204:	learn: 0.0301889	total: 157ms	remaining: 610ms
205:	learn: 0.0299916	total: 158ms	remaining: 609ms
206:	learn: 0.0298625	total: 158ms	remaining: 607ms
207:	learn: 0.0296213	total: 159ms	remaining: 605ms
208:	learn: 0.0295285	total: 159ms	remaining: 604ms
209:	learn: 0.0293585	total: 160ms	remaining: 602ms
210:	learn: 0.0291918	total: 161ms	remaining: 600ms
211:	learn: 0.0289994	total: 161ms	remaining: 599ms
212:	learn: 0.0288397	total: 162ms	remaining: 598ms
213:	learn: 0.0287234	total: 162ms	remaining: 596ms
214:	learn: 0.0285949	total: 163ms	remaining: 595ms
215:	learn: 0.0284429	total: 163ms	remaining: 593ms
216:	learn: 0.0283129	total: 164ms	remaining: 591ms
217:	learn: 0.0280712	total: 165ms	remaining: 591ms
218:	learn: 0.0279222	total: 166ms	remaining: 590ms
219:	learn: 0.0277636	total: 166ms	remaining: 590ms
220:	learn: 0.0276454	total: 167ms	remaining: 590ms
221:	learn: 0.0274750	total: 168ms	remaining: 589ms
222:	learn: 0.0273337	total: 169ms	remaining: 587ms
223:	learn: 0.0271858	total: 169ms	remaining: 586ms
224:	learn: 0.0270635	total: 170ms	remaining: 584ms
225:	learn: 0.0269191	total: 170ms	remaining: 583ms
226:	learn: 0.0267808	total: 171ms	remaining: 581ms
227:	learn: 0.0266645	total: 171ms	remaining: 580ms
228:	learn: 0.0265410	total: 172ms	remaining: 578ms
229:	learn: 0.0264222	total: 172ms	remaining: 577ms
230:	learn: 0.0262394	total: 173ms	remaining: 575ms
231:	learn: 0.0261513	total: 173ms	remaining: 574ms
232:	learn: 0.0259570	total: 174ms	remaining: 572ms
233:	learn: 0.0258184	total: 174ms	remaining: 571ms
234:	learn: 0.0256991	total: 175ms	remaining: 570ms
235:	learn: 0.0255821	total: 176ms	remaining: 569ms
236:	learn: 0.0254322	total: 176ms	remaining: 567ms
237:	learn: 0.0252836	total: 177ms	remaining: 566ms
238:	learn: 0.0251874	total: 177ms	remaining: 564ms
239:	learn: 0.0250567	total: 178ms	remaining: 563ms
240:	learn: 0.0249335	total: 178ms	remaining: 562ms
241:	learn: 0.0248122	total: 180ms	remaining: 563ms
242:	learn: 0.0247261	total: 181ms	remaining: 563ms
243:	learn: 0.0246153	total: 181ms	remaining: 562ms
244:	learn: 0.0245058	total: 182ms	remaining: 561ms
245:	learn: 0.0243693	total: 183ms	remaining: 560ms
246:	learn: 0.0242558	total: 183ms	remaining: 559ms
247:	learn: 0.0241123	total: 184ms	remaining: 558ms
248:	learn: 0.0240136	total: 185ms	remaining: 557ms
249:	learn: 0.0239306	total: 185ms	remaining: 556ms
250:	learn: 0.0238065	total: 186ms	remaining: 554ms
251:	learn: 0.0237206	total: 186ms	remaining: 553ms
252:	learn: 0.0236264	total: 187ms	remaining: 552ms
253:	learn: 0.0235036	total: 188ms	remaining: 552ms
254:	learn: 0.0233779	total: 188ms	remaining: 550ms
255:	learn: 0.0232199	total: 189ms	remaining: 549ms
256:	learn: 0.0230852	total: 190ms	remaining: 548ms
257:	learn: 0.0229869	total: 194ms	remaining: 557ms
258:	learn: 0.0229194	total: 194ms	remaining: 556ms
259:	learn: 0.0228324	total: 195ms	remaining: 556ms
260:	learn: 0.0227111	total: 196ms	remaining: 556ms
261:	learn: 0.0226117	total: 197ms	remaining: 555ms
262:	learn: 0.0225016	total: 198ms	remaining: 554ms
263:	learn: 0.0223370	total: 198ms	remaining: 553ms
264:	learn: 0.0222596	total: 199ms	remaining: 552ms
265:	learn: 0.0221684	total: 200ms	remaining: 551ms
266:	learn: 0.0220545	total: 200ms	remaining: 550ms
267:	learn: 0.0219509	total: 201ms	remaining: 549ms
268:	learn: 0.0218482	total: 201ms	remaining: 548ms
269:	learn: 0.0217384	total: 202ms	remaining: 547ms
270:	learn: 0.0216007	total: 203ms	remaining: 546ms
271:	learn: 0.0215329	total: 204ms	remaining: 546ms
272:	learn: 0.0213980	total: 205ms	remaining: 545ms
273:	learn: 0.0213028	total: 205ms	remaining: 544ms
274:	learn: 0.0212086	total: 206ms	remaining: 544ms
275:	learn: 0.0211046	total: 208ms	remaining: 546ms
276:	learn: 0.0210104	total: 209ms	remaining: 545ms
277:	learn: 0.0208894	total: 210ms	remaining: 544ms
278:	learn: 0.0207998	total: 210ms	remaining: 543ms
279:	learn: 0.0207210	total: 211ms	remaining: 542ms
280:	learn: 0.0206295	total: 212ms	remaining: 541ms
281:	learn: 0.0205705	total: 212ms	remaining: 540ms
282:	learn: 0.0205072	total: 213ms	remaining: 539ms
283:	learn: 0.0204287	total: 214ms	remaining: 539ms
284:	learn: 0.0203521	total: 214ms	remaining: 538ms
285:	learn: 0.0202710	total: 217ms	remaining: 541ms
286:	learn: 0.0201837	total: 217ms	remaining: 540ms
287:	learn: 0.0201112	total: 218ms	remaining: 539ms
288:	learn: 0.0200453	total: 219ms	remaining: 538ms
289:	learn: 0.0199609	total: 219ms	remaining: 537ms
290:	learn: 0.0198686	total: 220ms	remaining: 537ms
291:	learn: 0.0198051	total: 221ms	remaining: 536ms
292:	learn: 0.0197436	total: 222ms	remaining: 535ms
293:	learn: 0.0196146	total: 222ms	remaining: 534ms
294:	learn: 0.0195381	total: 223ms	remaining: 533ms
295:	learn: 0.0194448	total: 224ms	remaining: 532ms
296:	learn: 0.0193943	total: 224ms	remaining: 531ms
297:	learn: 0.0193120	total: 225ms	remaining: 530ms
298:	learn: 0.0192221	total: 226ms	remaining: 529ms
299:	learn: 0.0191609	total: 226ms	remaining: 528ms
300:	learn: 0.0190941	total: 227ms	remaining: 527ms
301:	learn: 0.0189813	total: 228ms	remaining: 526ms
302:	learn: 0.0189075	total: 228ms	remaining: 525ms
303:	learn: 0.0188515	total: 229ms	remaining: 524ms
304:	learn: 0.0187917	total: 230ms	remaining: 523ms
305:	learn: 0.0186803	total: 230ms	remaining: 522ms
306:	learn: 0.0185849	total: 231ms	remaining: 521ms
307:	learn: 0.0185198	total: 231ms	remaining: 520ms
308:	learn: 0.0184433	total: 232ms	remaining: 519ms
309:	learn: 0.0183862	total: 233ms	remaining: 518ms
310:	learn: 0.0183287	total: 233ms	remaining: 517ms
311:	learn: 0.0182725	total: 234ms	remaining: 517ms
312:	learn: 0.0182196	total: 235ms	remaining: 516ms
313:	learn: 0.0181193	total: 236ms	remaining: 515ms
314:	learn: 0.0180589	total: 237ms	remaining: 514ms
315:	learn: 0.0179835	total: 238ms	remaining: 515ms
316:	learn: 0.0178991	total: 239ms	remaining: 515ms
317:	learn: 0.0178441	total: 240ms	remaining: 516ms
318:	learn: 0.0177703	total: 241ms	remaining: 515ms
319:	learn: 0.0176993	total: 242ms	remaining: 514ms
320:	learn: 0.0176305	total: 243ms	remaining: 513ms
321:	learn: 0.0175835	total: 243ms	remaining: 512ms
322:	learn: 0.0175160	total: 244ms	remaining: 511ms
323:	learn: 0.0174661	total: 245ms	remaining: 510ms
324:	learn: 0.0174196	total: 245ms	remaining: 509ms
325:	learn: 0.0173678	total: 246ms	remaining: 508ms
326:	learn: 0.0173091	total: 246ms	remaining: 507ms
327:	learn: 0.0172301	total: 247ms	remaining: 507ms
328:	learn: 0.0171634	total: 248ms	remaining: 506ms
329:	learn: 0.0170758	total: 249ms	remaining: 505ms
330:	learn: 0.0170154	total: 250ms	remaining: 505ms
331:	learn: 0.0169443	total: 251ms	remaining: 504ms
332:	learn: 0.0168960	total: 251ms	remaining: 504ms
333:	learn: 0.0168544	total: 252ms	remaining: 503ms
334:	learn: 0.0167867	total: 253ms	remaining: 503ms
335:	learn: 0.0167249	total: 254ms	remaining: 502ms
336:	learn: 0.0166757	total: 255ms	remaining: 502ms
337:	learn: 0.0166217	total: 256ms	remaining: 501ms
338:	learn: 0.0165801	total: 256ms	remaining: 500ms
339:	learn: 0.0165121	total: 257ms	remaining: 499ms
340:	learn: 0.0164313	total: 258ms	remaining: 498ms
341:	learn: 0.0163790	total: 258ms	remaining: 497ms
342:	learn: 0.0163485	total: 259ms	remaining: 497ms
343:	learn: 0.0162888	total: 260ms	remaining: 496ms
344:	learn: 0.0162300	total: 261ms	remaining: 495ms
345:	learn: 0.0161774	total: 262ms	remaining: 496ms
346:	learn: 0.0161130	total: 263ms	remaining: 495ms
347:	learn: 0.0160296	total: 264ms	remaining: 495ms
348:	learn: 0.0159472	total: 265ms	remaining: 494ms
349:	learn: 0.0158798	total: 265ms	remaining: 493ms
350:	learn: 0.0158242	total: 266ms	remaining: 492ms
351:	learn: 0.0157729	total: 267ms	remaining: 491ms
352:	learn: 0.0157288	total: 267ms	remaining: 490ms
353:	learn: 0.0156817	total: 268ms	remaining: 489ms
354:	learn: 0.0156200	total: 268ms	remaining: 488ms
355:	learn: 0.0155655	total: 269ms	remaining: 487ms
356:	learn: 0.0155233	total: 270ms	remaining: 486ms
357:	learn: 0.0154756	total: 270ms	remaining: 485ms
358:	learn: 0.0154218	total: 271ms	remaining: 484ms
359:	learn: 0.0153670	total: 272ms	remaining: 483ms
360:	learn: 0.0153204	total: 272ms	remaining: 482ms
361:	learn: 0.0152667	total: 273ms	remaining: 481ms
362:	learn: 0.0151841	total: 274ms	remaining: 480ms
363:	learn: 0.0151264	total: 275ms	remaining: 481ms
364:	learn: 0.0150817	total: 276ms	remaining: 480ms
365:	learn: 0.0150353	total: 276ms	remaining: 479ms
366:	learn: 0.0149905	total: 277ms	remaining: 478ms
367:	learn: 0.0149384	total: 278ms	remaining: 477ms
368:	learn: 0.0148763	total: 278ms	remaining: 476ms
369:	learn: 0.0148194	total: 279ms	remaining: 475ms
370:	learn: 0.0147868	total: 280ms	remaining: 474ms
371:	learn: 0.0147085	total: 281ms	remaining: 474ms
372:	learn: 0.0146761	total: 281ms	remaining: 473ms
373:	learn: 0.0146308	total: 282ms	remaining: 472ms
374:	learn: 0.0145811	total: 284ms	remaining: 473ms
375:	learn: 0.0145364	total: 286ms	remaining: 475ms
376:	learn: 0.0144780	total: 287ms	remaining: 475ms
377:	learn: 0.0144255	total: 292ms	remaining: 480ms
378:	learn: 0.0143891	total: 293ms	remaining: 480ms
379:	learn: 0.0143464	total: 294ms	remaining: 480ms
380:	learn: 0.0143040	total: 295ms	remaining: 480ms
381:	learn: 0.0142546	total: 296ms	remaining: 479ms
382:	learn: 0.0142091	total: 297ms	remaining: 478ms
383:	learn: 0.0141560	total: 297ms	remaining: 477ms

CatBoostClassifier()

In [18]:
y_pred = model.predict(X_test)

print(f"Accuracy Score: {accuracy_score(y_test, y_pred)}")
print(f"Confusion Matrix: {confusion_matrix(y_test, y_pred)}")
print(f"Classification Report: {classification_report(y_test, y_pred)}")

Accuracy Score: 1.0
Confusion Matrix: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30