# **Pandas (Day-1)**

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./data/data.csv')

In [4]:
df.to_excel('awen_wala_data.xlsx')

In [5]:
df = pd.read_excel('awen_wala_data.xlsx')

In [6]:
# reading the excel file
df_xl = pd.read_excel('awen_wala_data.xlsx', sheet_name='Sheet1')

## Pands tips

In [7]:
print(df)

     Unnamed: 0  PROVINCE                   DIVISION  \
0             0    PUNJAB        BAHAWALPUR DIVISION
1             1    PUNJAB        BAHAWALPUR DIVISION
2             2    PUNJAB        BAHAWALPUR DIVISION
3             3    PUNJAB        BAHAWALPUR DIVISION
4             4    PUNJAB        BAHAWALPUR DIVISION
..          ...       ...                        ...
523         523  KPK/FATA  DERA ISMAIL KHAN DIVISION
524         524  KPK/FATA  DERA ISMAIL KHAN DIVISION
525         525  KPK/FATA  DERA ISMAIL KHAN DIVISION
526         526  KPK/FATA  DERA ISMAIL KHAN DIVISION
527         527  KPK/FATA  DERA ISMAIL KHAN DIVISION

                      DISTRICT         SUB DIVISION  AREA (sq.km)  \
0        BAHAWALNAGAR DISTRICT  BAHAWALNAGAR TEHSIL        1729.0
1        BAHAWALNAGAR DISTRICT     CHISHTIAN TEHSIL        1500.0
2        BAHAWALNAGAR DISTRICT    FORT ABBAS TEHSIL        2536.0
3        BAHAWALNAGAR DISTRICT    HAROONABAD TEHSIL        1295.0
4        BAHAWALNAGAR DISTRICT   MINCHINABAD TEHSIL        1818.0
..                         ...                  ...           ...
523  SOUTH WAZIRISTAN DISTRICT     SARAROGHA TEHSIL         813.0
524  SOUTH WAZIRISTAN DISTRICT      SERWEKAI TEHSIL         398.0
525  SOUTH WAZIRISTAN DISTRICT        TIARZA TEHSIL         734.0
526  SOUTH WAZIRISTAN DISTRICT    TOI KHULLA TEHSIL         567.0
527  SOUTH WAZIRISTAN DISTRICT          WANA TEHSIL        2315.0

     ALL SEXES (RURAL)  MALE (RURAL)  FEMALE (RURAL)  TRANSGENDER (RURAL)  \
0               619550        316864          302644                   42
1               540342        273788          266500                   54
2               361240        182655          178541                   44
3               382115        192278          189808                   29
4               452723        231506          221178                   39
..                 ...           ...             ...                  ...
523              98180         51479           46694                    7
524              54540         28695           25844                    1
525              45156         23649           21507                    0
526              50413         27462           22947                    4
527             153156         81342           71796                   18

     ...  POPULATION 1998 (RURAL)  ANNUAL GROWTH RATE (RURAL)  \
0    ...                   407768                        2.22
1    ...                   395983                        1.65
2    ...                   250959                        1.93
3    ...                   297343                        1.33
4    ...                   316593                        1.90
..   ...                      ...                         ...
523  ...                    72063                        1.64
524  ...                    31472                        2.93
525  ...                    37708                        0.95
526  ...                    36508                        1.71
527  ...                    90772                        2.79

     ALL SEXES (URBAN)  MALE (URBAN)  FEMALE (URBAN)  TRANSGENDER (URBAN)  \
0               193840         98391           95402                   47
1               149424         75546           73851                   27
2                61528         31360           30150                   18
3               142600         71345           71236                   19
4                72294         36694           35590                   10
..                 ...           ...             ...                  ...
523                  0             0               0                    0
524                  0             0               0                    0
525                  0             0               0                    0
526                  0             0               0                    0
527                  0             0               0                    0

     SEX RATIO (URBAN)  AVG HOUSEHOLD SIZE (URBAN)  POPULATION 1998 (URBAN)  \
0               103.13                        6.02                   133785
1               102.30                        6.01                   102287
2               104.01                        6.00                    34637
3               100.15                        6.02                    84424
4               103.10                        6.34                    37668
..                 ...                         ...                      ...
523               0.00                        0.00                        0
524               0.00                        0.00                        0
525               0.00                        0.00                        0
526               0.00                        0.00                        0
527               0.00                        0.00                        0

     ANNUAL GROWTH RATE (URBAN)
0                          1.97
1                          2.01
2                          3.06
3                          2.79
4                          3.48
..                          ...
523                        0.00
524                        0.00
525                        0.00
526                        0.00
527                        0.00

[528 rows x 22 columns]

In [8]:
528+21

549

In [9]:
# how the data looks like
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528 entries, 0 to 527
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  528 non-null    int64
 1   PROVINCE                    528 non-null    object
 2   DIVISION                    528 non-null    object
 3   DISTRICT                    528 non-null    object
 4   SUB DIVISION                528 non-null    object
 5   AREA (sq.km)                528 non-null    float64
 6   ALL SEXES (RURAL)           528 non-null    int64
 7   MALE (RURAL)                528 non-null    int64
 8   FEMALE (RURAL)              528 non-null    int64
 9   TRANSGENDER (RURAL)         528 non-null    int64
 10  SEX RATIO (RURAL)           528 non-null    float64
 11  AVG HOUSEHOLD SIZE (RURAL)  528 non-null    float64
 12  POPULATION 1998 (RURAL)     528 non-null    int64
 13  ANNUAL GROWTH RATE (RURAL)  528 non-null    float64
 14  ALL SEXES (URBAN)           528 non-null    int64
 15  MALE (URBAN)                528 non-null    int64
 16  FEMALE (URBAN)              528 non-null    int64
 17  TRANSGENDER (URBAN)         528 non-null    int64
 18  SEX RATIO (URBAN)           528 non-null    float64
 19  AVG HOUSEHOLD SIZE (URBAN)  528 non-null    float64
 20  POPULATION 1998 (URBAN)     528 non-null    int64
 21  ANNUAL GROWTH RATE (URBAN)  528 non-null    float64
dtypes: float64(7), int64(11), object(4)
memory usage: 90.9+ KB

In [13]:
df.head(3)

,Unnamed: 0,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
0,0,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR TEHSIL,1729.0,619550,316864,302644,42,...,407768,2.22,193840,98391,95402,47,103.13,6.02,133785,1.97
1,1,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,CHISHTIAN TEHSIL,1500.0,540342,273788,266500,54,...,395983,1.65,149424,75546,73851,27,102.30,6.01,102287,2.01
2,2,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,FORT ABBAS TEHSIL,2536.0,361240,182655,178541,44,...,250959,1.93,61528,31360,30150,18,104.01,6.00,34637,3.06

In [12]:
df.tail(3)

,Unnamed: 0,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
525,525,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TIARZA TEHSIL,734.0,45156,23649,21507,0,...,37708,0.95,0,0,0,0,0.0,0.0,0,0.0
526,526,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TOI KHULLA TEHSIL,567.0,50413,27462,22947,4,...,36508,1.71,0,0,0,0,0.0,0.0,0,0.0
527,527,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,WANA TEHSIL,2315.0,153156,81342,71796,18,...,90772,2.79,0,0,0,0,0.0,0.0,0,0.0

In [14]:
df.describe()

,Unnamed: 0,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),AVG HOUSEHOLD SIZE (RURAL),POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
count,528.00000,528.000000,5.280000e+02,5.280000e+02,5.280000e+02,528.000000,528.000000,528.000000,5.280000e+02,528.000000,5.280000e+02,5.280000e+02,5.280000e+02,528.000000,528.000000,528.000000,5.280000e+02,528.000000
mean,263.50000,1492.005871,2.462780e+05,1.252757e+05,1.209841e+05,18.174242,98.982614,6.277064,1.674280e+05,3.124792,1.408635e+05,7.284339e+04,6.799787e+04,22.276515,75.411269,4.406402,8.014457e+04,1.920814
std,152.56474,2039.453778,2.711898e+05,1.375630e+05,1.337169e+05,25.522248,26.812660,2.074947,1.783890e+05,9.577872,3.512463e+05,1.823492e+05,1.688725e+05,66.068127,49.687341,2.948336,2.023120e+05,2.098908
min,0.00000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000
25%,131.75000,425.000000,5.093450e+04,2.712725e+04,2.397900e+04,1.000000,101.105000,5.700000,3.527350e+04,1.440000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000
50%,263.50000,882.000000,1.652410e+05,8.413450e+04,8.204400e+04,10.000000,105.285000,6.310000,1.172065e+05,2.030000,4.325450e+04,2.198000e+04,2.099900e+04,3.000000,103.195000,5.755000,2.129800e+04,1.855000
75%,395.25000,1734.250000,3.129112e+05,1.605022e+05,1.522190e+05,25.000000,108.347500,7.200000,2.130542e+05,2.812500,1.178148e+05,6.030175e+04,5.746525e+04,19.000000,107.040000,6.340000,6.542225e+04,2.985000
max,527.00000,18374.000000,2.297375e+06,1.172995e+06,1.124167e+06,213.000000,139.380000,12.430000,1.044035e+06,100.000000,3.653616e+06,1.905921e+06,1.746900e+06,795.000000,297.810000,10.060000,2.075867e+06,19.780000

In [16]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,518,519,520,521,522,523,524,525,526,527
Unnamed: 0,0,1,2,3,4,5,6,7,8,9,...,518,519,520,521,522,523,524,525,526,527
PROVINCE,PUNJAB,PUNJAB,PUNJAB,PUNJAB,PUNJAB,PUNJAB,PUNJAB,PUNJAB,PUNJAB,PUNJAB,...,KPK/FATA,KPK/FATA,KPK/FATA,KPK/FATA,KPK/FATA,KPK/FATA,KPK/FATA,KPK/FATA,KPK/FATA,KPK/FATA
DIVISION,BAHAWALPUR DIVISION,BAHAWALPUR DIVISION,BAHAWALPUR DIVISION,BAHAWALPUR DIVISION,BAHAWALPUR DIVISION,BAHAWALPUR DIVISION,BAHAWALPUR DIVISION,BAHAWALPUR DIVISION,BAHAWALPUR DIVISION,BAHAWALPUR DIVISION,...,KOHAT DIVISION,KOHAT DIVISION,DERA ISMAIL KHAN DIVISION,DERA ISMAIL KHAN DIVISION,DERA ISMAIL KHAN DIVISION,DERA ISMAIL KHAN DIVISION,DERA ISMAIL KHAN DIVISION,DERA ISMAIL KHAN DIVISION,DERA ISMAIL KHAN DIVISION,DERA ISMAIL KHAN DIVISION
DISTRICT,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR DISTRICT,BAHAWALPUR DISTRICT,BAHAWALPUR DISTRICT,BAHAWALPUR DISTRICT,BAHAWALPUR DISTRICT,BAHAWALPUR DISTRICT,...,ORAKZAI DISTRICT,ORAKZAI DISTRICT,SOUTH WAZIRISTAN DISTRICT,SOUTH WAZIRISTAN DISTRICT,SOUTH WAZIRISTAN DISTRICT,SOUTH WAZIRISTAN DISTRICT,SOUTH WAZIRISTAN DISTRICT,SOUTH WAZIRISTAN DISTRICT,SOUTH WAZIRISTAN DISTRICT,SOUTH WAZIRISTAN DISTRICT
SUB DIVISION,BAHAWALNAGAR TEHSIL,CHISHTIAN TEHSIL,FORT ABBAS TEHSIL,HAROONABAD TEHSIL,MINCHINABAD TEHSIL,AHMADPUR EAST TEHSIL,BAHAWALPUR CITY TEHSIL,BAHAWALPUR SADDAR TEHSIL,HASILPUR TEHSIL,KHAIRPUR TAMEWALI TEHSIL,...,LOWER TEHSIL,UPPER TEHSIL,BIRMIL TEHSIL,LADHA TEHSIL,MAKIN TEHSIL,SARAROGHA TEHSIL,SERWEKAI TEHSIL,TIARZA TEHSIL,TOI KHULLA TEHSIL,WANA TEHSIL
AREA (sq.km),1729.0,1500.0,2536.0,1295.0,1818.0,1738.0,1490.0,745.0,1490.0,993.0,...,565.0,299.0,923.0,466.0,404.0,813.0,398.0,734.0,567.0,2315.0
ALL SEXES (RURAL),619550,540342,361240,382115,452723,902476,0,467938,340747,221431,...,107323,63885,104282,110842,58646,98180,54540,45156,50413,153156
MALE (RURAL),316864,273788,182655,192278,231506,461525,0,239541,171117,112952,...,53767,32299,54323,57755,30906,51479,28695,23649,27462,81342
FEMALE (RURAL),302644,266500,178541,189808,221178,440889,0,228346,169620,108476,...,53550,31582,49948,53080,27738,46694,25844,21507,22947,71796
TRANSGENDER (RURAL),42,54,44,29,39,62,0,51,10,3,...,6,4,11,7,2,7,1,0,4,18
SEX RATIO (RURAL),104.7,102.73,102.3,101.3,104.67,104.68,0.0,104.9,100.88,104.13,...,100.41,102.27,108.76,108.81,111.42,110.25,111.03,109.96,119.68,113.3
AVG HOUSEHOLD SIZE (RURAL),6.1,6.15,6.32,6.15,6.29,6.53,0.0,6.33,6.03,6.22,...,8.16,7.04,9.44,6.36,6.35,7.57,7.2,7.99,9.34,10.19
POPULATION 1998 (RURAL),407768,395983,250959,297343,316593,601406,62916,314428,246218,157049,...,65416,84060,58512,72278,30528,72063,31472,37708,36508,90772
ANNUAL GROWTH RATE (RURAL),2.22,1.65,1.93,1.33,1.9,2.16,0.0,2.11,1.72,1.82,...,2.63,1.43,3.08,2.27,3.49,1.64,2.93,0.95,1.71,2.79
ALL SEXES (URBAN),193840,149424,61528,142600,72294,176110,682116,107948,115613,41492,...,0,0,0,0,0,0,0,0,0,0
MALE (URBAN),98391,75546,31360,71345,36694,90003,350186,62009,57743,20981,...,0,0,0,0,0,0,0,0,0,0
FEMALE (URBAN),95402,73851,30150,71236,35590,86081,331842,45927,57853,20507,...,0,0,0,0,0,0,0,0,0,0
TRANSGENDER (URBAN),47,27,18,19,10,26,88,12,17,4,...,0,0,0,0,0,0,0,0,0,0
SEX RATIO (URBAN),103.13,102.3,104.01,100.15,103.1,104.56,105.53,135.02,99.81,102.31,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AVG HOUSEHOLD SIZE (URBAN),6.02,6.01,6.0,6.02,6.34,6.28,5.91,5.98,6.09,5.75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
POPULATION 1998 (URBAN),133785,102287,34637,84424,37668,116891,356626,72610,71295,26854,...,0,0,0,0,0,0,0,0,0,0
ANNUAL GROWTH RATE (URBAN),1.97,2.01,3.06,2.79,3.48,2.18,3.47,2.11,2.57,2.31,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
df.tail()

,Unnamed: 0,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
523,523,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,SARAROGHA TEHSIL,813.0,98180,51479,46694,7,...,72063,1.64,0,0,0,0,0.0,0.0,0,0.0
524,524,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,SERWEKAI TEHSIL,398.0,54540,28695,25844,1,...,31472,2.93,0,0,0,0,0.0,0.0,0,0.0
525,525,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TIARZA TEHSIL,734.0,45156,23649,21507,0,...,37708,0.95,0,0,0,0,0.0,0.0,0,0.0
526,526,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TOI KHULLA TEHSIL,567.0,50413,27462,22947,4,...,36508,1.71,0,0,0,0,0.0,0.0,0,0.0
527,527,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,WANA TEHSIL,2315.0,153156,81342,71796,18,...,90772,2.79,0,0,0,0,0.0,0.0,0,0.0